FactoryBot.define do

  factory :execution_environment, class: "::ForemanAnsibleDirector::ExecutionEnvironment" do
    sequence(:name) { |n| "execution_environment_#{n}" }
    sequence(:base_image_url) { |n| "quay.io/ansible/base-ee:latest" }
    ansible_version { '2.20.0' }
    association :organization

    sequence(:content_hash) { "9cefe04e" } # This is the content hash for a default env generated by this
  end

  factory :execution_environment_content_unit, class: "ForemanAnsibleDirector::ExecutionEnvironmentContentUnit" do
    association :execution_environment
    association :content_unit
    association :content_unit_version

    after(:build) do |eecu| if eecu.content_unit_version && eecu.content_unit
                              eecu.content_unit_version.versionable = eecu.content_unit
                            end
    end
  end
end