---
name: Conventional Commits

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  commit_check:
    name: Conventional Commits
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3

      - uses: webiny/action-conventional-commits@v1.3.1
        with:
          allowed-commit-types: "feat,fix,chore,style,refactor,perf,test,build,ci"
